### ISSUE TITLE
fatal error C1083: opensslconf.h”: No such file or directory

### ISSUE THREAD

**Issue by liquidzym** [bakercp/ofxHTTP#10]
another weird thing is that when compiling example_basic_websocket_server,always complaining include\Poco/Crypto/OpenSSLInitializer.h(45): fatal error C1083: Cannot open include file:“openssl/opensslconf.h”: No such file or directory

with debug,no such error,but output this
https://github.com/bakercp/ofxHTTP/issues/9

btw,there's also warning about two same name files
warning MSB8027: Two or more files with the name of Utils.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are ......\addons\ofxHTTP\libs\ofxHTTP\Utils\src\Utils.cpp, ......\addons\ofxJSONRPC\libs\ofxJSONRPC\src\Utils.cpp.

thxs!

**Comment by BartZuidervaart** [comment]
I am having the same issue with codeblocks. How do I fix this?

**Comment by bakercp** [comment]
@BartZuidervaart did you try the solutions linked above?  What version of openFrameworks are you using?

**Comment by BartZuidervaart** [comment]
I am using version 0.8.4. The problem is that the solution mentioned above is for visualstudio and don't know how to translate the problem to codeblocks to fix it. The files in libs/openFrameworksCompiled/project don't align with the files described in the visualstudio fix. I've searched the files for a similar problem but everything seems fine to me.

**Comment by BartZuidervaart** [comment]
for anyone who experiences the same problem

http://forum.openframeworks.cc/t/fatal-error-openssl-opensslconf-h-no-such-file-or-directory/20870/1
